apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: kube-logging
spec:
  ports:
  - port: 5044
    targetPort: beats
  selector:
    type: logstash
  clusterIP: None
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: kube-logging
spec:
  selector:
    matchLabels:
      type: logstash
  template:
    metadata:
      labels:
        type: logstash
        srv: srv-logstash
    spec:
      containers:
      - image: docker.io/kubeimages/logstash:7.9.3 # 该镜像支持arm64和amd64两种知构
        name: logstash
        ports:
        - containerPort: 5044
          name: beats
        command :
        - logstash
        - '-f'
        - '/etc/logstash_c/logstash.conf'
        env:
        - name: "XPACK_MONITORING_ELASTICSEARCH_HOSTS"
          value: "http://elasticsearch-logging:9200"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/logstash_c/
        - name: config-yml-volume
          mountPath: /usr/share/logstash/config/
        - name: timezone
          mountPath: /etc/localtime
        resources: # logstash一定要加上资源限剂，避免对其他业务造成资源抢占影响
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 512m
            memory: 512Mi
      volumes:
      - name: config-volume
        configMap:
          name: logstash-conf
          items:
          - key: logstash.conf
            path: logstash.conf
      - name: timezone
        hostPath:
          path: /etc/localtime
      - name: config-yml-volume
        configMap:
          name: logstash-yml
          items:
            - key: logstash.yml
              path: logstash.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-conf
  namespace: kube-logging
  labels:
    type: logstash
data:
  logstash.conf: |-
    input {
      beats {
        port => 5044
      }
    }
    filter {
      if [kubernetes][container][name]== "nginx-ingress-controller" {
        json {
          source => "message"
          target => "ingress_log"
        }

        if [ingress_log][requesttime] {
          mutate {
            convert =>["[ingress_log][requesttime]", "float"]
          }
        }

        if [ingress_log][upstreamtime] {
          mutate {
            convert =>["[ingress_log][upstreamtime]", "float"]
          }
        }

        if [ingress_log][status] {
          mutate {
            convert =>["[ingress_log][status]", "float"]
          }
        }
        
        
        if [ingress_log][httphost] and [ingress_log][uri] {
          mutate {
            add_field => {"[ingress_log][entry]" => "%{[ingress_log][httphost]}%{[ingress_log][uri]}"}
          }

          mutate {
            split => ["[ingress_log][entry]","/"]
          }
          
          if [ingress_log][entry][1] {
            mutate {
                add_field => {"[ingress_log][entrypoint]" => "%{[ingress_log][entry][0]}/%{[ingress_log][entry][1]}"}
                remove_field => "[ingress_log][entry]"
            }
          
          } else {
          
            mutate {
                add_field => {"[ingress_log][entrypoint]" => "%{[ingress_log][entry][0]}/"}
                remove_field => "[ingress_log][entry]"
            }
          }
        
        }
      
      }
      
      
   
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch-logging:9200"]
        codec => json
        index => "logstash-%{+YYYY.MM.dd}" # 索引名称以logstash+日志进行每日新建
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-yml
  namespace: kube-logging
  labels:
    type: logstash
data:
  logstash.yml: |-
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.hosts: http://elasticsearch-logging:9200
