piVersian: apps/v1
kind: statefulset
metadata:
  name: grafana-core
  namespace: kube-monitoring
  labels:
    app: grafana
    component: core
spec:
  serviceName: "grafana"
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
      app: grafana
      component: core
    spec:
      containers:
      - image: grafana/grafana:6.5.3
      name: grafana-core
      imagePullPolicy: IfNotPresent
      env: # The following  variablesset up basic auth twith the default admin user and adinin password.
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "false"
        # - name: GF_AUTH_ANONYMOUS_ORG_ROLE
        #   value: Admin
      readinessProbe:
        httpGet:
          path: /login
          port: 3000 # initialDelaySeconds: 30 # timeoutSeconds:1
        volumeMounts:
        - name: grafana-persistent-storage
          mountPath: /var/lib/grafana
          subPath: grafana
  volumeClaimTemplates:
  - metadata:
    name: grafana-persistent-storage
  spec:
    storageClassName: managed-nfs-storage
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "lGi"
