apiVersion: v1
kind: Pod
metadata:
  name: test-pvc-pd
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx-volume
    volumeMounts:
    - mountPath: /usr/share/nginx/html # 挂载到容器的哪个目录
      name: test-volume #挂载哪个volume
  volumes :
    - name: test-volume
      persistentVolumeClaim:
        claimName: nfs-pvc # pvc的名字
