apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pd1
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: test-container
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: test-volume
  volumes:
  - name: test-volume
    nfs:
     server: 192.168.146.135 # 网络存储服务地址
     path: /home/nfs/rw/www/wolfcode # 网络存储路径,需要创建好
     readOnly: false # 是否只读
