apiVersion: v1
kind: Endpoints 
metadata:
  name: nginx-svc-external
  labels:
    app: nginx
  namespace: default
subsets:
- addresses:
  - ip: 120.78.159.117
  ports:
  - name: web 
    port: 80
    protocol: TCP 
